spring.application.name=audit-engine
# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_vault_db
spring.datasource.username=postgres
spring.datasource.password=Kingtimmy_2007

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# AI Audit Engine Integrations
ai.api.url=https://api.openai.com/v1
ai.api.key=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
ai.api.model=gpt-4o

# Set the maximum allowed file size limits (e.g., 50MB per file, 50MB per request)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB